charts/fluent-bit/Chart.yaml, charts/fluent-bit/README.md, charts/fluent-bit/templates/daemonset.yaml, charts/fluent-bit/templates/service.yaml, charts/fluent-bit/values.yaml
Since Fluent-bit supports network inputs (TCP and in the future UDP) it makes sense that the helm chart have the ability to expose additional ports at both the daemonset and the service level.
This PR adds an additional variable extraPorts which is a list of objects, and the different helm templates will use the variable values to add additional exposed ports to the daemonset and service.
An example usage:
To expose TCP port 1234
The variable extraPorts can be set to:
extraPorts:
- name: tcp
protocol: TCP
port: 1234
containerPort: 1234
That will result in a service that looks like this:
.
.
.
type: ClusterIP
ports:
- port: 2020
targetPort: http
protocol: TCP
name: http
- name: tcp
targetPort: http2
protocol: TCP
port: 1234
selector:
app.kubernetes.io/name: fluent-bit
.
.
.
and a daemonset …
=> Add variable for additional exposed Ports/Services

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/clusterrole.yaml
Similar to what the AWS Fluent-bit chart does to enable processing all namespaces:
https://github.com/aws/eks-charts/blob/master/stable/aws-for-fluent-bit/templates/clusterrole.yaml
=> Adding necessary resources/verbs to process logs in all namespaces

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/daemonset.yaml, charts/fluent-bit/templates/deployment.yaml, charts/fluent-bit/values.yaml
This adds the ability add custom labels to fluent-bit pods. Works for both DaemonSet and Deployment types.
=> Adds podLabels

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/_pod.tpl, charts/fluent-bit/values.yaml
**What this PR does / why we need it:**
Adding possibility to set a custom dnsConfig for the pods. Pod's DNS Config field enable users more control on the DNS settings for the pods.
**Use-case example**
Fluent-bit pods /etc/resolv.conf ndots:5 (default) and output Elasticsearch external domain example.elastic.com, syscall will try to resolve it sequentially going through all local search domains first and then resolve the absolute name only at last, which puts load on the DNS resolver and impacts the performance of the applications. Tuning dnsConfig for Fluent-bit pod allows us to avoid such scenarios and resolve the absolute name at first and cache the positive response.
Similar work done in the past in previous stable repository. [ref.](https://github.com/helm/charts/pull/22419)
=> Add ability for custom dnsConfig

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/tests/test-connection.yaml, charts/fluent-bit/values.yaml
Allow the image used for helm tests to be configured.  This permits the use of private registries.
=> Configurable test pod image

charts/fluent-bit/Chart.yaml, charts/fluent-bit/dashboards/fluent-bit.json, charts/fluent-bit/templates/configmap-dashboards.yaml, charts/fluent-bit/values.yaml
I've added the [documented](https://docs.fluentbit.io/manual/administration/monitoring#grafana-dashboard)  _fluent-bit Grafana_ [dashboard](https://github.com/fluent/fluent-bit-docs/blob/master/monitoring/dashboard.json) to the _Helm_ chart as a configmap that the _Grafana_ sidecar can pick up and install. I've added the `dashboards.enabled` variable to turn it on.
The dashboard needed minor changes to support the sidecar which could be merged back into the documentation.
Fixes issue https://github.com/fluent/helm-charts/issues/61.
=> [fluent-bit] Add Grafana dashboard

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/configmap.yaml, charts/fluent-bit/templates/networkpolicy.yaml, charts/fluent-bit/templates/prometheusrule.yaml, charts/fluent-bit/values.yaml
Hi,
I know that this PR embed more than one modification, so should I split it on three different one, or can I keep all changes on this one?
1. **Add networkPolicy**:  be able to limit access to metrics endpoint only to prometheus instances for exemple
2. **Add PrometheusRule**: embed Alerting in the chart instead of putting all rules on a single place (only if prometheus CRDs are installed)
3. **Be able to customize configurations across environments**: We have different environments with the same configuration except Cluster depending ones (environment, uri, ...). 
This change allows to use values in configuration
```yaml
config:
service: |
[SERVICE]
Flush 1
Daemon Off
Log_Level info
Parsers_File parsers.conf
Parsers_File custom_parsers.conf
HTTP_Server On
HTTP_Listen 0.0.0.0
HTTP_Port …
```
=> [fluent-bit]: add prometheusrule, networkpolicy and use tpl in configmap

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/configmap-dashboards.yaml, charts/fluent-bit/values.yaml
Signed-off-by: Alexis Martinier <a.martinier@gmail.com>
This change allows to specify annotations on dashboards configmap
**use case**:  
if grafana sidecar is configured with `sidecar.dashboards.folderAnnotation: grafana/folder` ([grafana configuration](https://github.com/grafana/helm-charts/blob/main/charts/grafana/README.md#configuration)), we can change the dashboard folder
```yaml
dashboard:
enabled: true
labelKey: grafana_dashboard
annotations:
grafana/folder: logging
```
=> feat(fluent-bit): add custom annotations to dashboards configmap

charts/fluent-bit/Chart.yaml, charts/fluent-bit/dashboards/fluent-bit.json
The purpose is to give a more specific dashboard for Fluent-bit
The actual one display some metrics not relatives to fluent-bit (eg: CPU and memory usage, limit, request not scoped to fluent-bit) and doesn't provide ability to filter by pod
Below, the changes on proposed dashboard
* Number of fluent-bit
* Number of ready nodes
* Number of not ready nodes
* Input bytes processing rate
* Output bytes processing rate
* Input records processing rate 
* Output records processing rate 
* Output retry/failed rate 
* Output error rate
* Global % CPU usage
* Global % CPU request
* Global % CPU limit 
* Global % memory usage 
* Global % memory request 
* Global % memory limit
* Pod filter
* fluent-bit CPU usage
* fluent-bit CPU request 
* fluent-bit memory usage
* fluent-bit memory request 
* …
=> [fluent-bit]: proposal - improve dashboard

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/_pod.tpl, charts/fluent-bit/templates/configmap-luascripts.yaml, charts/fluent-bit/templates/configmap.yaml, charts/fluent-bit/templates/daemonset.yaml, charts/fluent-bit/templates/deployment.yaml, charts/fluent-bit/values.yaml
This PR allows us to add an unlimited number of lua scripts to the extraLuaScripts section in the values file. The scripts will be mounted to the /fluent-bit/scripts folder.
To use the script, you need to add a section with a lua filter that uses this script. For example:
[FILTER]
Name lua
Match *
script /fluent-bit/scripts/<script_name>.lua
call <lua_function>
=> added the ability to add custom lua scripts to the values file

charts/fluent-bit/Chart.yaml
- Bump appVersion to latest fluent-bit version ([1.7.0](https://fluentbit.io/announcements/v1.7.0))
- Bump chart version to 0.12.2
=> [fluent-bit] Bump appVersion to 1.7.0

.github/workflows/lint-test.yaml
Fixing ct unit test so that it uses the ct.yaml config file.
Fixed #86
=> Update ct to use ct.yaml config

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/_pod.tpl, charts/fluent-bit/values.yaml
`extraContainers` property accepts an array of Pod containers
=> [fluent-bit] Allow user-defined sidecar containers

charts/fluentd/Chart.yaml, charts/fluentd/templates/servicemonitor.yaml, charts/fluentd/values.yaml
Hi
this PR extend to servicemonitor to allow custom
* metricRelabelings 
* relabelings:
example add the nodename label to fluentd metrics
```
relabelings:
- action: replace
sourceLabels:
- __meta_kubernetes_pod_node_name
targetLabel: nodename
```
The joblabel is defaulting to `.Release.Name` if not otherwise set.
=> [fluentd] extend servicemonitor with metric relabel config

charts/fluent-bit/Chart.yaml, charts/fluent-bit/dashboards/fluent-bit.json, charts/fluent-bit/templates/configmap-dashboards.yaml
The dashboard had a typo in it and also wasn't templated with the fullname tpl variable for the release. This allows the JSON to pass through the template engine to properly take on the fullname created within the helper tpls.
It looks ugly because escaping variables in go template engine isn't pretty, but it is fully functional from my testing.
=> Add Templating to the Dashboard

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/_pod.tpl, charts/fluent-bit/values.yaml
When you use the fluent-bit helm chart as a sub-chart and you set a custom livenessProbe that is not httpGet based, a duplicate probe gets set.
```
livenessProbe:
exec:
command:
- powershell
- Get-Process
- ProcessName
- fluent-bit
httpGet:
path: /
port: http
```
Normally you would just set httpGet to be null in the parent chart, and it would override the value. However, there is an open issue with helm [helm/helm/issues/9136](https://github.com/helm/helm/issues/9136) where that functionality is not working.
I'm looking to use an exec livenessProbe, so if there is a preferred implementation I can adjust my pr.
This if/else way allows you to over write the httpGet probe.
=> [fluent-bit] Add support exec livenessProbe

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/configmap-dashboards.yaml
It allows to deploy the chart in the same namespace more than once without conflicts.
=> [fluent-bit] Add release name in dashboard name

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/_pod.tpl, charts/fluent-bit/values.yaml
This patch make the Charts to support the initContainers, user can dynamically add initContainers via the values.yaml.
Original issue: #81
=> [fluent-bit] Support the initContainers from the values.yaml

charts/fluentd/Chart.yaml, charts/fluentd/templates/prometheusrules.yaml, charts/fluentd/values.yaml
When prometheusrule is enable i got the following error:
```
Error: template: fluentd/templates/_helpers.tpl:15:14: executing "fluentd.fullname" at <.Values.fullnameOverride>: can't evaluate field Values in type []interface {}
helm.go:81: [debug] template: fluentd/templates/_helpers.tpl:15:14: executing "fluentd.fullname" at <.Values.fullnameOverride>: can't evaluate field Values in type []interface {}
```
This PR fix this issue.
I also added some example alerts
=> [fluentd] fixed prometheusrule template injection

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/_pod.tpl, charts/fluent-bit/values.yaml
Signed-off-by: Salicorne <timothee.raboeuf@gmail.com>
Since fluent-bit does not support the IP Address certificate SubjectAlternateName when validating a remote certificate in the HTTP output, it can be useful to provide custom hostAliases in the Helm chart to match a DNS SAN of the certificate.
=> [fluent-bit] Add optional hostAliases

.github/workflows/lint-test.yaml, .github/workflows/release.yaml, charts/fluent-bit/Chart.yaml, charts/fluent-bit/ci/ci-values.yaml, charts/fluent-bit/templates/_pod.tpl, charts/fluent-bit/templates/clusterrole.yaml, charts/fluent-bit/templates/psp.yaml, charts/fluent-bit/values.yaml
This PR adds support to Fluent Bit v1.8 with the following chart changes as well as tidying up the comments in values.yaml for automatic formatting and updating the GitHub actions.
- Upgrade fluent-bit image to v1.8.1.
- Use new health check endpoint for readiness.
- Use liveness and rediness config from values, this means setting `httpGet: {}` if you want to use exec.
- Multiline docker and cri logs in the default tail input.
- Support for the `Use_Kubelet true` in the Kubernetes filter config by enabling setting `rbac.nodeAccess: true`, `hostNetwork: true` and `dnsPolicy: ClusterFirstWithHostNet`.
- Customisable log level via `logLevel` value.
Fixes #135, fixes #119.
=> [fluent-bit] Support v1.8

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/_pod.tpl, charts/fluent-bit/templates/configmap.yaml, charts/fluent-bit/values.yaml
This allows adding more files to /fluent-bit/etc without having to externally define volume and volume mounts. Instead, we can add arbitrary files and file names by providing key/val pairs in the `.Values.config.extraFiles` variable in values.yaml. The key becomes the filename, the value becomes the file content.
This is useful for cases where someone needs to add a `Streams_File` or `Plugins_File` inside the `[SERVICE]` section (like I do).
In theory, it might be nice to move custom_parsers.conf to this structure, but I did not touch that for backwards compatibility.
=> [fluent-bit] Add extraFiles to add conf to /fluent-bit/etc

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/service.yaml, charts/fluent-bit/values.yaml
I made it possible to configure the node port option to fluent-bit service. It is a just simple change related to this.
In my case, it is useful to use the node port when I tried to receive forwarded data from the cluster outside.
Signed-off-by: jonghyun <heiwais25@gmail.com>
=> [fluent-bit] Add  NodePort option to Service

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/_pod.tpl, charts/fluent-bit/values.yaml
I suggest to use a different values than the existing one (`initContainers`).
So there is no breaking changes.
Fix #159.
=> feat(fluent-bit) Add initContainersTpl values. Fix #159

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/_pod.tpl, charts/fluent-bit/values.yaml
The following changes have been made.
- Change `initContainers` logic
- Support templating when value is a string
- No templating when value is an array due to inconsistent behaviour
- Remove whitespace from templates
- Bump chart minor version (major is 0) as breaking change
=> [fluent-bit] Update initContainers logic

charts/fluentd/Chart.yaml
•	Looks like icon url no longer returned an image:
•	Fixed with:
=> [fluentd] Icon URL not working #150

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/_pod.tpl, charts/fluent-bit/values.yaml, charts/fluentd/Chart.yaml, charts/fluentd/templates/_pod.tpl, charts/fluentd/values.yaml
This PR adds the possibility to add lifecycle management to the pods. That may be helpful to let the pod running long enough so that it can properly be deregistered from a load balancer.
=> add(fluentd,fluent-bit): added lifecycle object

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/configmap.yaml
Signed-off-by: Eli Algranti <eli.algranti@gmail.com>
This the same as PR-187, which I closed by mistake, with merge conflicts fixed and patch update instead of minor.
Templating the value of extraFiles allows pulling the content of extra files from e.g. globals, and provides feature parity with the rest of the values that make up fluent-bit's configuration.
=> Templates extraFiles values

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/configmap-dashboards.yaml, charts/fluent-bit/values.yaml
Allows to define a different namespace for dashboard's ConfigMap. 
Signed-off-by: jkosecki <jan.kosecki91@gmail.com>
=> [Fluent-bit] Allow defining namespace for dashboard's ConfigMap

charts/fluent-bit/Chart.yaml, charts/fluent-bit/values.yaml
This PR fixes a typo present in `values.yaml` of the `fluent-bit` chart.
=> Fix a typo in additionalLabels in fluent-bit chart

charts/fluentd/Chart.yaml, charts/fluentd/values.yaml
With the current configuration, the entrypoint uses the wrong configuration file:
```
root@fluentd-m7qqg:/home/fluent# cat /proc/1/cmdline
tini--/fluentd/entrypoint.shroot@fluentd-m7qqg:/home/fluent# ps aux | grep fluentd
root           1  0.0  0.0   8308  1936 ?        Ss   07:35   0:00 tini -- /fluentd/entrypoint.sh
root           7  6.3  0.0 140144 63556 ?        Sl   07:35   0:01 ruby /fluentd/vendor/bundle/ruby/2.6.0/bin/fluentd -c /fluentd/etc/fluent.conf -p /fluentd/plugins --gemfile /fluentd/Gemfile -r /fluentd/vendor/bundle/ruby/2.6.0/gems/fluent-plugin-elasticsearch-4.3.3/lib/fluent/plugin/elasticsearch_simple_sniffer.rb
root          90 54.0  0.0  87884 39952 ?        R    07:36   0:00 /usr/local/bin/ruby -Eascii-8bit:ascii-8bit /fluentd/vendor/bundle/ruby/2.6.0/bin/fluentd -c …
```
=> Fixing FLUENTD_CONF to point to /etc/fluent/fluent.conf

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/_pod.tpl, charts/fluent-bit/values.yaml
Add `envWithTpl` variable that support injecting Environment Variables with supporting values coming from `--set <variable>=<value>`, by using the function `tpl`.
This does not impact the behavior of the Environment Variables defined under `env`, so this is not a breaking change.
Example of values.yaml:
```
mySuperSecret: ""
envWithTpl:
MY_SUPER_SECRET: "{{ .Values.mySuperSecret }}"
```
Example of helm command:
```
export MY_SUPER_SECRET="password123"
helm upgrade fluent-bit --install --debug --values ./values.yaml --set mySuperSecret=${MY_SUPER_SECRET} fluent/fluent-bit
```
This is a similar fix as https://github.com/fluent/helm-charts/issues/186 that is provided by the PR https://github.com/fluent/helm-charts/pull/202, but uses `range` and does not touch the existing `env` logic.
=> Add envWithTpl variable

charts/fluentd/Chart.yaml, charts/fluentd/templates/_pod.tpl, charts/fluentd/templates/daemonset.yaml, charts/fluentd/templates/deployment.yaml, charts/fluentd/templates/statefulset.yaml, charts/fluentd/values.yaml
In this PR i added the ability to better control the deployment of the single fluentd pods.
We are experiencing issues that our pods aren't registered in the clouds load balancer (as they stay in "initial" state longer than needed due to cloud providers restrictions).
To ensure that enough instances are available during a deployment (or simply during scaling activities), i've added two new values:
* terminationGracePeriodSeconds
* minReadySeconds
This will allow the pod to finish all traffic, being deregistered from the load balancer and then exit (due to the pre-stop lifecycle policy added earlier).
New pods will now wait minReadySeconds until letting the deployment controller move on to the next pod.
I chose 30 seconds for terminationGracePeriodSeconds, as i assume this to be the …
=> added minReadySeconds and terminationGracePeriodSeconds for fluentd

charts/fluent-bit/Chart.yaml
This PR update fluent-bit image to 1.8.12 and bump the chart version and `artifacthub.io/changes` annotation accordingly.
=> Update fluent-bit image to 1.8.12

charts/fluent-bit/Chart.yaml
This PR update fluent-bit image to 1.8.13 and bump the chart version and add `artifacthub.io/changes` annotation accordingly.
=> Update fluent-bit image to 1.8.13

charts/fluent-bit/Chart.yaml, charts/fluent-bit/values.yaml
In newer versions, we are using a new CNAME path to expose the container images:
cr.fluentbit.io
this is just a CNAME that resolves back to Docker Hub registry but give us more
flexibility and information.
Signed-off-by: Eduardo Silva <eduardo@calyptia.com>
=> fluent bit: update repository path

charts/fluent-bit/Chart.yaml
This PR updates Fluent Bit to [v1.8.15](https://github.com/fluent/fluent-bit/releases/tag/v1.8.15) and should be merged before the chart moves on to the v1.9.x series.
=> feat[fluent-bit]: Update image to v1.8.15

charts/fluentd/Chart.yaml, charts/fluentd/templates/service.yaml, charts/fluentd/values.yaml
Setting the loadBalancerIP and externalTrafficPolicy is useful when using the Services as type LoadBalancer.
We need these settings when receiving syslog via a LoadBalancer IP.
Follow up pull request to #221.
=> Add ability to optionally set loadBalancerIP and externalTrafficPolicy on Service

charts/fluent-bit/Chart.yaml
To be honest, I am not sure if anything specific needs to be added/changed in the charts `values.yaml`. I straight forward rely on the assumption of a semver minor increase of flb from 1.8x to 1.9.0 and the fact, that most settings are configured in this helm chart by writing the raw config files so or so.
=> Update fluent-bit image to 1.9.3

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/clusterrole.yaml, charts/fluent-bit/templates/scc.yaml, charts/fluent-bit/values.yaml
Because of Openshift uses security API different from Kubernetes,
there are additional object called SecurityContextConstraints required
for access logs on Openshift nodes. I add this object, in state as it's
uses in Openshift's cluster-logging-operator.
Signed-off-by: Kirill Thirteen <thethir13en@gmail.com>
=> Add initial Openshift SCC support for Fluent-Bit

charts/fluent-bit/Chart.yaml
This PR update the Fluent Bit image to latest stable version 1.9.4 and bump the chart version accordingly and add a change annotation about it.
=> Update fluent-bit image to 1.9.4

charts/fluent-bit/Chart.yaml
This PR updates the Fluent Bit image to [v1.9.7](https://github.com/fluent/fluent-bit/releases/tag/v1.9.7) ([release notes](https://fluentbit.io/announcements/v1.9.7/)).
=> feat[fluent-bit]: Updated image to v1.9.7

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/configmap.yaml, charts/fluent-bit/values.yaml
This will add [upstream server](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/upstream-servers) config option to the configmap. This includes multiple or none upstream configuration files to be generated.
Related PR: https://github.com/fluent/helm-charts/pull/69
Signed-off-by: dominykasn <dominykas.norkus@hostinger.com>
=> Add upstream values option to configmap

charts/fluent-bit/Chart.yaml
This PR updates Fluent Bit image to 1.9.8, document that in the artifacthub.io/changes annotation as usual and bump the chart version by one.
=> Update fluent-bit image to 1.9.8

charts/fluent-bit/Chart.yaml
This PR updates Fluent bit to the latest version [v1.9.9](https://fluentbit.io/announcements/v1.9.9/).
=> feat[fluent-bit]: Updated image to v1.9.9

charts/fluent-bit/Chart.yaml, charts/fluent-bit/README.md, charts/fluent-bit/values.yaml
This PR mark `config.upstream` as deprecated corresponding to the conclusion in #271.
Closes: #270
=> [fluent-bit] Mark `config.upstream` as deprecated

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/_pod.tpl, charts/fluent-bit/templates/daemonset.yaml, charts/fluent-bit/templates/deployment.yaml, charts/fluent-bit/values.yaml
In pull request I've add ability to controll time which kubernetes shoud wait with pod termination after deregistering target in load balancer. 
Our use case is decrease logs lossess arisen during pods rotation.
To be compilant with fluent-d configuration I also add minReadySeconds support (https://github.com/fluent/helm-charts/pull/204)
Signed-off-by: Jacek <jacek.socha@gmail.com>
=> Add terminationGracePeriodSeconds and minReadySeconds for fluent-bit

charts/fluent-bit/Chart.yaml
Closes #274.
Signed-off-by: Leonardo Taccari <leonardo@faire.ai>
=> Update fluent-bit image to 2.0.4

charts/fluent-bit/Chart.yaml, charts/fluent-bit/values.yaml
Since Fluent Bit 1.9 the configuration file URL was moved under the classic mode section to distinguish it with the YAML configuration.
This PR updates it to avoid the broken URL and continue to point out to the classic configuration format preferred by the Helm chart.
=> [fluent-bit] Update Configuration File URL

charts/fluent-bit/Chart.yaml
This PR updates to latest fluent-bit 2.0.6.
=> [fluent-bit] Update `fluent-bit` image to 2.0.6

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/service.yaml, charts/fluent-bit/values.yaml
This PR exposes support for setting fields relevant to `type: LoadBalancer` services. https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/#ServiceSpec
=> [fluent-bit] Add support for service.loadBalancerSourceRanges and service.loadBalancerClass

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/clusterrole.yaml, charts/fluent-bit/templates/psp.yaml, charts/fluent-bit/values.yaml
Starting with Kubernetes version 1.25, the developers have decided to completely remove the PSP API. Since this causes Helm deployments to fail, the PSP deployment must be explicitly disabled for newer Kubernetes versions. This PR adds a capability version check to the PSP configuration.
=> fix: disable fluent-bit psp config

charts/fluent-bit/Chart.yaml
This PR updates fluent-bit image to latest 2.0.8 release and bump changes annotations as usual.
=> [fluent-bit] Update image to 2.0.8

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/configmap-dashboards.yaml, charts/fluent-bit/values.yaml
Supports user defined value for the Grafana dashboard label. Adds feature parity with the fluentd chart, to support non-standard values.
Backwards compatable default value of the string value "1".
This should close #332
=> feat: adds support for grafana dashboard label value

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/_helpers.tpl, charts/fluent-bit/templates/_pod.tpl, charts/fluent-bit/templates/tests/test-connection.yaml, charts/fluent-bit/values.yaml
Related to #356 
- Adds ability to reference images using image digest rather than tag.
=> feat(fluent-bit): add image reference by digest

charts/fluent-operator/Chart.yaml, charts/fluent-operator/crds/fluentbit.fluent.io_clusterfilters.yaml, charts/fluent-operator/crds/fluentbit.fluent.io_clusterfluentbitconfigs.yaml, charts/fluent-operator/crds/fluentbit.fluent.io_clusterinputs.yaml, charts/fluent-operator/crds/fluentbit.fluent.io_clusteroutputs.yaml, charts/fluent-operator/crds/fluentbit.fluent.io_filters.yaml, charts/fluent-operator/crds/fluentbit.fluent.io_fluentbits.yaml, charts/fluent-operator/crds/fluentbit.fluent.io_outputs.yaml, charts/fluent-operator/crds/fluentd.fluent.io_clusterfilters.yaml, charts/fluent-operator/crds/fluentd.fluent.io_clusteroutputs.yaml, charts/fluent-operator/crds/fluentd.fluent.io_filters.yaml, charts/fluent-operator/crds/fluentd.fluent.io_fluentds.yaml, charts/fluent-operator/crds/fluentd.fluent.io_outputs.yaml, charts/fluent-operator/templates/fluent-operator-deployment.yaml, charts/fluent-operator/templates/fluentbit-clusterinput-tail.yaml, charts/fluent-operator/templates/fluentbit-fluentBit.yaml, charts/fluent-operator/templates/fluentbit-input-node-exporter-metrics-edge.yaml, charts/fluent-operator/templates/fluentbit-input-prometheus-scrape-metrics-edge.yaml, charts/fluent-operator/templates/fluentbit-output-prometheus-remote-write-edge.yaml, charts/fluent-operator/templates/fluentd-fluentd.yaml, charts/fluent-operator/values.yaml
Update fluent-operator to newest v2.3.0 release from [fluent/fluent-operator](https://github.com/fluent/fluent-operator/tree/v2.3.0).
=> Update fluent-operator from v2.2.0 to v2.3.0

charts/fluent-bit/Chart.yaml, charts/fluent-bit/ci/ci-values.yaml, charts/fluent-bit/dashboards/fluent-bit.json, charts/fluent-bit/templates/servicemonitor.yaml, charts/fluent-bit/values.yaml
This PR fixes the Fluent Bit chart Grafana dashboard scope to work when there are multiple pods with similar names. It also updates Grafana dashboard components and schemas.
=> feat(fluent-bit): Updated dashboard scope

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/_pod.tpl
When the chart is deployed with `hotReload.enabled: true`, because of the duplicated `volumeMounts` key only the second block was being picked up:
This:
```yaml
volumeMounts:
- name: config
mountPath: /watch/config
volumeMounts:
- name: luascripts
mountPath: /watch/scripts
```
Would become this:
```yaml
volumeMounts:
- name: luascripts
mountPath: /watch/scripts
```
With this PR the block now looks like this:
```yaml
volumeMounts:
- name: config
mountPath: /watch/config
- name: luascripts
mountPath: /watch/scripts
```
=> Remove duplciated `volumeMounts` in `reloader` container

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/_helpers.tpl, charts/fluent-bit/templates/clusterrole.yaml, charts/fluent-bit/templates/scc.yaml, charts/fluent-bit/values.yaml
- This commit breaks Openshift compatibility with previous versions
- Add ability to provide existing SecurityContextConstraints name instead of create new one
- Add ability to add annotations for SecrutiryContextConstraints resource, created with the chart
- Add common labels for SecurityContextConstraints
- Improve variables naming
=> [Fluent-Bit] Improve Openshift support, allow to use existing SCCs

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/_helpers.tpl
This PR should fix https://github.com/fluent/helm-charts/issues/399.
It was tested on OKD 4.11 (Openshift upstream) cluster.
=> [Fluent Bit] Fix Openshift SCC name template

charts/fluent-bit/Chart.yaml, charts/fluent-bit/values.yaml
After this PR(#384) my fluent-bit deployment stopped working well as reported on this issue(https://github.com/fluent/helm-charts/issues/392).
The problem happens only if I use the debug image in my Kubernetes cluster to be able to access to the shell if needed.
To remain the same behaviour that we were having before this PR, I suggest to set the fluent-bit binary as a command.
This won´t cause any problem to the main docker image, it only adds compatibility with the image with suffix **-debug**. 
You can check the differentes between both docker images in this [link](https://github.com/fluent/fluent-bit/blob/master/dockerfiles/Dockerfile), where you can see that the production image has the entrypoint but the debug no.
Another option is to add the binary to the first line of the args, …
=> feat(fluent-bit) Set command binary for fluent-bit

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/clusterrole.yaml, charts/fluent-bit/values.yaml
Hey,
We recently deployed the latest chart (0.37.0) and enabled kubernetes_events according to [this doc](https://docs.fluentbit.io/manual/pipeline/inputs/kubernetes-events#simple-configuration-file)
However the ClusterRole that is created by the chart is missing the events resources access and thus fluent-bit starts throwing errors and no events are collected.
Simply adding `events` to the ClusterRole resource resolves the issue.
I placed it behind a flag as events input is not used by default and that might add unnecessary load on fluent-bit and the services that consume it, let me know if you would like to change the logic or values structure here.
=> [fluent-bit] Enable cluster role events access by values

charts/fluentd/Chart.yaml, charts/fluentd/templates/_pod.tpl, charts/fluentd/values.yaml
Added a variable in `values.yaml` (`outputType`) that corresponds to the type of output plugin you're using and changes to the _pod.tpl `$defaultTag` to pull the correct image since left alone will pull the wrong image.
changes to `_pod.tpl`:
```yaml
{{- define "fluentd.pod" -}}
{{- $defaultTag := printf "%s-debian-%s-1.0" (.Chart.AppVersion) (.Values.outputType) -}}
{....}
```
changes to `values.yaml`:
```yaml
outputType: elasticsearch7
```
changes to `Chart.yaml` (just updated the AppVersion since it was used by default to pull version of fluentd):
```yaml
appVersion: v1.16.2
```
Scenario:
i'm testing `fluentd` and `fluentbit` with `opensearch` without the changes the pod pulls a fluentd-daemonset elasticsearch image that doesn't have opensearch plugin inside it to run my output config.
=> feature ✨(fluentd): added changes to defaultTag in the _pod.tpl

CONTRIBUTING.md
Added a small note to the contributing guide to clarify how contributions to the fluent-operator Helm chart should be made (i.e. in fluent/fluent-operator first).
Please let me know if you'd like me to make any changes - would be happy to do so!
=> feat: add note to contributing guide regarding contributions to fluent-operator

charts/fluentd/Chart.yaml, charts/fluentd/templates/service.yaml, charts/fluentd/values.yaml
Allows users to deploy fluentd without any service, in case they want to only use log forwarding and don't care about serving metrics
=> feat(fluentd): Allow service to be optional for the daemonset deployment; enabled by default

.github/dependabot.yaml, .github/workflows/lint-test.yaml, .github/workflows/release.yaml
This PR updates the GitHub Actions workflows to use the latest versions, it also adds support for Dependabot to create PRs to keep these up to date.
=> ci: Updated GH actions

charts/fluent-bit/Chart.yaml, charts/fluent-bit/dashboards/fluent-bit.json
Replace the statically configured prometheus datasource uid with the placeholder to fix the following Grafana error:
=> [fluent-bit] Fix Grafana dashboard error

charts/fluentd/Chart.yaml, charts/fluentd/templates/ingress.yaml, charts/fluentd/values.yaml
Add Ingress resource to fluentd for Deployment/StatefulSet options.
=> [fluentd] Add Ingress.

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/servicemonitor.yaml
Signed-off-by: Sébastien Larivière <sebastien.lariviere@goto.com>
Keeps the path to `v1` by default, but allows it to be updated to `v2` if needed.
=> feat(fluent-bit): ServiceMonitor path values

charts/fluentd/Chart.yaml, charts/fluentd/templates/tests/test-connection.yaml, charts/fluentd/values.yaml
Added a few tweaks to make the current default values a bit more complete from a working out of the box perspective and to enable the existing test to pass.
Related to #440
=> Correct fluentd helm tests

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/_helpers.tpl, charts/fluent-bit/templates/ingress.yaml, charts/fluent-bit/values.yaml
=> feat(fluent-bit): Added support for ingress.annotations tpl rendering and image pull policy change

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/_pod.tpl, charts/fluent-bit/values.yaml
The same as https://github.com/fluent/helm-charts/pull/163, support tpl in extraContainers.
- Support templating when value is a string
- No templating when value is an array due to inconsistent behaviour
=> feat(fluent-bit): Support tpl in extraContainers

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/service.yaml, charts/fluent-bit/values.yaml
This PR extends the fluentbit Service with ExternalIPs, if any is defined.
I've followed same pattern many [other](https://github.com/search?q=externalIPs%3A+%7B%7B-+toYaml+.Values.service.externalIPs+%7C+nindent+4+%7D%7D&type=code) charts are already using.
Small update but might be helpful to others as well.
=> Add posibility to assign ExternalIPs  to fluentbit's Service

charts/fluent-bit/Chart.yaml, charts/fluent-bit/dashboards/fluent-bit.json, charts/fluent-bit/templates/_helpers.tpl
Conflict in UIDs of Grafana dashboard when running multiple Fluent Bit Helm Release.
Fixes #499
=> Create unqiue uid for grafana fluent-bit dashboard

charts/fluent-bit/Chart.yaml
Upgrade Fluent-bit to v3.0.4 to patch [CVE-2024-4323](https://nvd.nist.gov/vuln/detail/CVE-2024-4323)
Since the release is ready https://github.com/fluent/fluent-bit/releases with the image patched, this PR serves only the purpose of bumping the appVersion.
Additional info:
- https://vulners.com/cve/CVE-2024-4323
- https://www.tenable.com/blog/linguistic-lumberjack-attacking-cloud-services-via-logging-endpoints-fluent-bit-cve-2024-4323
=> Patch Fluent-Bit CVE-2024-4323

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/clusterrole.yaml
this change allows fluent-bit to scrape metrics from Kubelet /metrics and /metrcis/cadvisor endpoints
=> feat(fluent-bit): give fluent-bit access to kubelet metrics

charts/fluent-bit/Chart.yaml, charts/fluent-bit/ci/ci-values.yaml, charts/fluent-bit/dashboards/fluent-bit.json, charts/fluent-bit/values.yaml
=> Make UID of grafana Fluent Bit dashboard configurable in values

charts/fluent-bit/Chart.yaml, charts/fluent-bit/values.yaml
The following PR updates the Fluent Bit image to the latest version available: v3.1.10:
- https://fluentbit.io/announcements/v3.1.10/
In addition, I am reverting the change that was done in the PullPolicy for the main image from 'IfNotPresent' to 'Always'. As you know, we don't do user-telemetry in Fluent Bit, our only indicator of adoption is the number of deployments/downloads from the containers registry. Users can always tweak this value, so I am just changing the default as the one we had before.
=> feat(fluent-bit): Updated image to v3.1.10

charts/fluent-bit/Chart.yaml, charts/fluent-bit/values.yaml
This PR updates the Fluent Bit version to [3.2.1](https://github.com/fluent/fluent-bit/releases/tag/v3.2.1). It also reverts the change to image pull policy made in #565 which serves no purpose, besides inflating the Docker pulls, given the image reference is immutable; the major downside of this is that it can cause Docker Hub rate limits to quickly be hit as every time a container starts on a node the image index will be pulled even if the image already exists. For reference the reason the chart originally had a pull policy of `Always` was that it used a mutable tag (such as `v2`) that was allowed to update on each container start.
CC @patrick-stephens
=> feat(fluent-bit): Updated image to 3.2.1

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/psp.yaml, charts/fluent-bit/templates/scc.yaml, charts/fluent-bit/values.yaml
EDIT: after discussions, we decided to make seLinux and runAs policies configurable instead of changing the default.
When creating a securityContextContraint for Openshift, the helm chart currently set the selinux strategy to `MustRunAs`, but this might lead to permission errors if you are using selinux in the node and you want to mount an host folder with an HostPath.
I think there is no reason for disallowing selinux context to be changed for the fluentbit deployment. Also, this is the same behavior used by red hat for their cluster logging operator that deploys fluentd.
https://github.com/openshift/cluster-logging-operator/blob/master/internal/auth/securitycontextconstraint.go#L46
=> Add option to configure seLinux and runAs policies

charts/fluent-bit/Chart.yaml, charts/fluent-bit/templates/_pod.tpl, charts/fluent-bit/templates/serviceaccount.yaml, charts/fluent-bit/values.yaml
Setting `automountServiceAccountToken` to false is often enforced in regulated clusters. Adding it to pod spec with the default value true.
=> [Helm Chart]: Add automountServiceAccountToken to pod spec
