fluent/helm-charts

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/README.md
- charts/fluent-bit/templates/daemonset.yaml
- charts/fluent-bit/values.yaml
> [fluent-bit] Allow overriding image tag

- charts/fluentd/Chart.yaml
- charts/fluentd/templates/_pod.tpl
> fix: indentation breaking extraVolumes and others

- charts/fluentd/Chart.yaml
- charts/fluentd/templates/clusterrole.yaml
- charts/fluentd/templates/podsecuritypolicy.yaml
- charts/fluentd/values.yaml
Adds podsecuritypolicy.yaml template to fluentd chart and suggestions provided by @naseemkullah
> Adds podsecuritypolicy.yaml template to fluentd chart and suggestions

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/README.md
- charts/fluent-bit/templates/service.yaml
- charts/fluent-bit/values.yaml
Add option to configure service labels for fluent-bit chart
> fluent-bit: Add service labels option

- charts/fluent-bit/Chart.yaml
> chore(fluent-bit): update appVersion 1.5.4

- charts/fluent-bit/Chart.yaml
> chore(fluent-bit): update appVersion 1.5.6

- charts/fluent-bit/Chart.yaml
> chore(fluent-bit): update appVersion 1.5.7

- charts/fluent-bit/Chart.yaml
> chore(fluent-bit): update appVersion 1.6.3

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/templates/daemonset.yaml
- charts/fluent-bit/templates/deployment.yaml
- charts/fluent-bit/values.yaml
- RollingUpdate default set
- configurable through values
Signed-off-by: Sebastian Brandt <sbrandt@d2iq.com>
> chore(fluent-bit): adding RollingUpdate

- charts/fluent-bit/Chart.yaml
> chore(fluent-bit): update appVersion 1.6.5

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/templates/_pod.tpl
- charts/fluent-bit/templates/configmap.yaml
- charts/fluent-bit/values.yaml
Hi,
a small update to be able to use an external config map into fluentbit
> [fluent-bit] add ability to use an external configmap

- charts/fluent-bit/Chart.yaml
> chore(fluent-bit): update appVersion 1.6.6

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/templates/deployment.yaml
> Fixed invalid field deploy.spec.updateStrategy

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/templates/_pod.tpl
- charts/fluent-bit/values.yaml
solves: https://github.com/fluent/helm-charts/issues/50
> [fluent-bit] make health checks configurable

- charts/fluent-bit/Chart.yaml
> chore(fluent-bit): update appVersion 1.6.7

- charts/fluent-bit/Chart.yaml
> chore(fluent-bit): update appVersion 1.6.10

- charts/fluentd/Chart.yaml
- charts/fluentd/templates/daemonset.yaml
- charts/fluentd/templates/deployment.yaml
- charts/fluentd/values.yaml
Changes:
* Adds PodLabels to fluentd chart (already available in the same fashion in fluent-bit)
> Add podLabels to fluentd

- charts/fluentd/Chart.yaml
- charts/fluentd/dashboards/fluentd.json
- charts/fluentd/templates/_pod.tpl
- charts/fluentd/templates/configmap-dashboards.yaml
- charts/fluentd/templates/files.conf/systemd.yaml
- charts/fluentd/templates/servicemonitor.yaml
- charts/fluentd/values.yaml
* Bump Chart
* Fix missing excape on etcd regex
* Fix deleted .Capabilities check on serviceMonitor
* Fix default docker tag
* Fix fluentd.conf file path
* Grafana dashboard improvements
@stevehipwell you had some comments about the grafana dashboard __input
You want to provide some examples?
> [fluentd] Fixes for v0.2.0 release

- charts/fluent-bit/Chart.yaml
> chore(fluent-bit): update appVersion 1.7.1

- charts/fluent-bit/Chart.yaml
- updating appVersion to the latest fluent-bit version
> chore(fluent-bit): update appVersion 1.7.2

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/templates/_pod.tpl
- charts/fluent-bit/values.yaml
I would like to set the mounts to be configurable. This helps support running fluent-bit on windows.
Signed-off-work: Alec Rajeev <alecinthecloud@gmail.com>
> Add support for configurable volume mounts

- charts/fluentd/Chart.yaml
- charts/fluentd/templates/configmap-dashboards.yaml
- charts/fluentd/values.yaml
This PR fix an issue that the value from dashboards.namespace is ignored
> [fluentd] added namespace to configmap-dashboards

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/templates/_pod.tpl
- charts/fluent-bit/values.yaml
Adding support for a configurable command and arg.
> Add support for configurable command and arg

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/templates/psp.yaml
- charts/fluent-bit/values.yaml
Signed-off-by: Abhinav Khanna <abhinav.khanna@salesforce.com>
closes #93
> feat: added psp annotations

- charts/fluent-bit/Chart.yaml
> [fluent-bit] Upgrade image to v1.7.3

- charts/fluent-bit/Chart.yaml
> [fluent-bit] Upgrade image to v1.7.4

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/templates/configmap-dashboards.yaml
Signed-off-by: Francisco Robles Martín <franrobles93@gmail.com>
> [fluent-bit] Fix: pass root of the context instead of range context

- charts/fluentd/Chart.yaml
- charts/fluentd/templates/_pod.tpl
- charts/fluentd/values.yaml
Signed-off-by: Friedrich Vogl <friedrich.vogl@gmail.com>
> [fluentd] made livenessProbe and readinessProbe properties configurable

- .gitignore
- charts/fluentd/Chart.yaml
- charts/fluentd/templates/hpa.yaml
- charts/fluentd/values.yaml
Signed-off-by: Arturo Alonso <thefang12@gmail.com>
> [fluentd] add hpa support

- charts/fluent-bit/Chart.yaml
> [fluent-bit] Upgrade to v1.7.5

- charts/fluent-bit/Chart.yaml
> [fluent-bit] Upgrade to v1.7.6

- charts/fluent-bit/Chart.yaml
> [fluent-bit] Upgrade to v1.7.7

- charts/fluent-bit/Chart.yaml
- Updated Fluent Bit image to `v1.7.8`
> [fluent-bit] Upgrade to v1.7.8

- charts/fluent-bit/Chart.yaml
- Updated Fluent Bit image to v1.7.9
> [fluent-bit] Updated image to v1.7.9

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/templates/psp.yaml
Fixes https://github.com/fluent/helm-charts/issues/141.
> [fluent-bit] Fix PSP hostNetwork value reference

- charts/fluentd/Chart.yaml
Signed-off-by: Diogo Guerra <diogo.filipe.tomas.guerra@cern.ch>
> Add dioguerra to fluentd maintainers

- charts/fluent-bit/Chart.yaml
- Updated Fluent Bit image to v1.8.3
- Bumped chart patch version
> [fluent-bit] Update image to v1.8.3

- charts/fluentd/Chart.yaml
- charts/fluentd/templates/daemonset.yaml
- charts/fluentd/templates/deployment.yaml
Added checksumming for fluentd config to fix issue #129
> [fluentd] added checksumming for configs

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/templates/_pod.tpl
- charts/fluent-bit/templates/configmap.yaml
- charts/fluent-bit/values.yaml
Derived from #33
This just resolves conflicts.
The [main work](https://github.com/mikutas/fluent-helm-charts/commit/f5cfaf236264c92314ff1e8d15c80ad1af18d940) is done by @mbarrien.
> [fluent-bit] Add extraFiles to add conf to /fluent-bit/etc

- charts/fluent-bit/Chart.yaml
- Updated Fluent Bit image to v1.8.5
- Bumped chart patch version
> [fluent-bit] Update to v1.8.5

- charts/fluent-bit/Chart.yaml
- Updated Fluent Bit image to v1.8.6
- Bumped chart patch version
> [fluent-bit] update to v1.8.6

- charts/fluentd/values.yaml
Fixed a (2) small typo in the values.yaml while reading through it
> fix(fluentd): typo in values.yaml

- charts/fluent-bit/Chart.yaml
- Updated Fluent Bit image to v1.8.7
- Bumped chart patch version
> [fluent-bit] Update to v1.8.7

- .github/CODEOWNERS
- charts/fluent-bit/Chart.yaml
I'm happy to accept the offer from @naseemkullah (via Slack) to help maintain the Fluent Bit Helm chart.
> chore(fluent-bit): add stevehipwell to maintainers

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/README.md
Related to https://github.com/fluent/helm-charts/issues/31
Closes #31 
- Improved README, added section about how to use Lua scripts for filtering.
> Added how to lua script to README

- charts/fluentd/Chart.yaml
Signed-off-by: Sherif Ayad <sherif.k.ayad@gmail.com>
> [FluentD] upgraded to fluentd v1.12.4

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/templates/pdb.yaml
Signed-off-by: tombokombo <tombo@sysart.tech>
> fix pdb matchLabels

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/templates/NOTES.txt
- charts/fluentd/Chart.yaml
- charts/fluentd/templates/NOTES.txt
Nothing big. Just ordered the commans in `NOTES.txt` so they can just be copied and executed.
Signed-off-by: bender316 <bender316@gmail.com>
> chore: fix order of build information commands

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/templates/_pod.tpl
- charts/fluent-bit/values.yaml
> Use values for default container port

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/values.yaml
Related to this [issue 208](https://github.com/fluent/helm-charts/issues/208).
Let me know if you would like additional content to this PR, but I think it should be pretty basic.
> Add `flush` param as chart value

- charts/fluent-bit/Chart.yaml
Straight forward update of fluent-bit patch version from 1.8.13 to 1.8.14.
> Update fluent-bit image to 1.8.14

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/templates/service.yaml
- charts/fluent-bit/values.yaml
Add ability to set ClusterIP address instead of using automatically defined
> fluent-bit: add ability to define ClusterIP IP-address

- charts/fluentd/Chart.yaml
- charts/fluentd/templates/_pod.tpl
- charts/fluentd/values.yaml
Add section to support initContainers for fluentd.
> Add initContainers to fluentd

- charts/fluentd/Chart.yaml
Closes: https://github.com/fluent/helm-charts/issues/236
Closes: https://github.com/fluent/helm-charts/issues/206
Signed-off-by: Diogo Guerra <diogo.filipe.tomas.guerra@cern.ch>
> Update fluentd from v1.12.4 to v1.14.6

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/templates/servicemonitor.yaml
- charts/fluent-bit/values.yaml
Signed-off-by: garcia.ryan <garcia.ryan@solute.us>
For issue https://github.com/fluent/helm-charts/issues/252
> [fluent-bit] serviceMonitor tlsConfig and scheme values

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/templates/tests/test-connection.yaml
- charts/fluent-bit/values.yaml
It should be possible to disable the tests.
This addition is fully backwards compatible.
> [fluent-bit] feat: possibility to disable tests

- charts/fluent-bit/Chart.yaml
This PR update fluent-bit image to 2.0.5.
> Update fluent-bit image to 2.0.5

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/templates/vpa.yaml
- charts/fluent-bit/values.yaml
Adding vpa support as requested: #307
> [FEAT] adding vpa support

- charts/fluent-bit/Chart.yaml
> [fluent-bit]: Updated imge to v2.0.9

- charts/fluent-operator/Chart.yaml
- charts/fluent-operator/crds/fluentbit.fluent.io_clusterfilters.yaml
- charts/fluent-operator/crds/fluentbit.fluent.io_fluentbits.yaml
- charts/fluent-operator/crds/fluentd.fluent.io_clusteroutputs.yaml
- charts/fluent-operator/crds/fluentd.fluent.io_outputs.yaml
- charts/fluent-operator/templates/fluent-operator-clusterRole.yaml
- charts/fluent-operator/templates/fluent-operator-deployment.yaml
- charts/fluent-operator/values.yaml
Upgraded fluent-operator to the latest v2.0.1, and also upgraded the related images of fluentbit and fluentd.
Signed-off-by: dehaocheng <dehaocheng@kubesphere.io>
> Upgrade Fluent-operator to v2.0.1

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/templates/configmap-dashboards.yaml
- charts/fluent-bit/templates/configmap-luascripts.yaml
- charts/fluent-bit/templates/configmap.yaml
- charts/fluent-bit/templates/daemonset.yaml
- charts/fluent-bit/templates/deployment.yaml
- charts/fluent-bit/templates/hpa.yaml
- charts/fluent-bit/templates/ingress.yaml
- charts/fluent-bit/templates/networkpolicy.yaml
- charts/fluent-bit/templates/pdb.yaml
- charts/fluent-bit/templates/prometheusrule.yaml
- charts/fluent-bit/templates/service.yaml
- charts/fluent-bit/templates/serviceaccount.yaml
- charts/fluent-bit/templates/servicemonitor.yaml
- charts/fluent-bit/templates/tests/test-connection.yaml
- charts/fluent-bit/templates/vpa.yaml
- charts/fluent-bit/values.yaml
Use `.Release.Namespace ` to render `namespace` for the fluent-bit resources
> feat(fluent-bit): define namespace for the k8s resources

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/templates/configmap-dashboards.yaml
Problem described in #335.
Closes #335
> [fluent-bit] Use Helm release specific Grafana dashboard filenames

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/templates/_pod.tpl
This PR fixes Lua script changes not being reflected when a hot-reload triggers.
> fix(fluent-bit): Fixed hot-reload for lua scripts

- charts/fluent-bit/Chart.yaml
> feat(fluent-bit): Updated image to v2.2.1

- charts/fluent-bit/Chart.yaml
> feat(fluent-bit): Updated image to v3.1.0

- charts/fluent-bit/Chart.yaml
> feat(fluent-bit): Updated image to v3.1.1

- charts/fluent-bit/Chart.yaml
> feat(fluent-bit): Updated image to v3.1.2

- charts/fluent-bit/Chart.yaml
> feat(fluent-bit): Updated image to v3.1.3

- charts/fluent-bit/Chart.yaml
> feat(fluent-bit): Updated image to v3.1.4

- charts/fluent-bit/Chart.yaml
> feat(fluent-bit): Updated image to v3.1.5

- charts/fluent-bit/Chart.yaml
> feat(fluent-bit): Updated image to v3.1.6

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/ci/ci-values.yaml
- charts/fluent-bit/values.yaml
> feat(fluent-bit): Updated configmap-reload image to 0.14.0

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/templates/tests/test-connection.yaml
> feat(fluent-bit): Updated image to v3.2.2

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/ci/ci-values.yaml
- charts/fluent-bit/templates/_pod.tpl
- charts/fluent-bit/values.yaml
https://github.com/fluent/fluent-bit/issues/9718
It would be good to be able to define more paths which should be watched from the hot reload functionality.
> [fluent-bit] Add support for additional watch paths in hot reload

- charts/fluent-bit/Chart.yaml
* Updates fluent-bit to 3.2.6
* Fixes CVE-2024-12133
> feat(fluent-bit): Updated image to 3.2.6

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/README.md
- charts/fluent-bit/ci/ci-values.yaml
- charts/fluent-bit/templates/configmap-luascripts.yaml
- charts/fluent-bit/values.yaml
This change allows Lua scripts templating.
#381 proposed something very similar, but it was closed.
> feat(fluent-bit): add lua scripts templating

- charts/fluent-bit/Chart.yaml
> feat(fluent-bit): Updated image to v3.2.7

- charts/fluent-bit/Chart.yaml
> feat(fluent-bit): Updated image to v3.2.8

- charts/fluent-bit/Chart.yaml
- charts/fluent-bit/templates/service.yaml
- charts/fluent-bit/values.yaml
I added loadBalancerIP to service.
fix #128
> feat(fluent-bit): add loadBalancerIP

- charts/fluent-bit/Chart.yaml
https://fluentbit.io/announcements/v4.0.1/
https://fluentbit.io/announcements/v4.0.0/
> feat(fluent-bit): Updated image to v4.0.1

- .github/workflows/lint-test.yaml
https://github.com/fluent/helm-charts/actions/runs/15448780655/job/43485353387?pr=614#step:6:17 https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Fix GHA deprecation of the ::set-output function
